w3c/mediacapture-main

- getusermedia.html
see also https://github.com/jsoref/mediacapture-main/commit/3821459f4ad52e12ccb2d7fb4509062cc7d7697f#commitcomment-9165769
> using a single type of quote and apostrophe

- getusermedia.html
This change uses a single constraint evaluation algorithm for both
device selection in getUserMedia and device reconfiguration in
applyConstraints.
> Constraint algorithm rewrite.

- getusermedia.html
> put links to task sources definitions

- getusermedia.html
> note about API on device info for input and output

- getusermedia.html
s/etting dictionar/ettings dictionar/
> settings (plural) dictionary

- getusermedia.html
> reword event handler descriptions to make their circumstances clearer

- getusermedia.html
> use proper text for link-less applyConstraints

- getusermedia.html
see https://github.com/w3c/mediacapture-main/issues/114#issuecomment-73332618
> remove sentence about sourceType change (doesn't happen)

- getusermedia.html
> define fitness distance when ideal is not specified

- getusermedia.html
> add link to constraints def in selectsettings

- getusermedia.html
> clarify enumerateDevices access model

- getusermedia.html
per https://github.com/w3c/mediacapture-main/issues/147#issuecomment-83602413
> remove "kind" argument of getSupportedConstraint

- getusermedia.html
(3 other issues are still in the doc after this; separate pull requests to come)
> Remove outdated issues in the doc

- .travis.yml
- getusermedia.html
(detected while preparing for LC publication)
> Broken fragment

- getusermedia.html
This procedure will be referenced by the webrtc-pc spec.
> Add steps describing the procedure to update a track's muted state

- getusermedia.html
> Add serializer to MediaDeviceInfo.

- getusermedia.html
See individual commit messages for details.
> [Issue  #174] Move sanity checks to sync section of getUserMedia algorithm and tidy up

- getusermedia.html
Intended to address https://github.com/w3c/mediacapture-main/issues/180
> replaced asynchronously with in parallel

- getusermedia.html
A PR that will partially fulfill #162.  See discussion in #170.
> Change AbortError from a MediaStreamError to a DOMException

- getusermedia.html
Partially fulfills #162. See also #170.
> Change PermissionDeniedError to a SecurityError DOMException

- getusermedia.html
Partially fulfills #162. See also #170.
> Change SourceAvailableError to a NotReadableError DOMException

- getusermedia.html
per issue #161, intended to replace PR #165
> Referring to html5.1 for describing srcObject in media elements.

- getusermedia.html
- getusermedia.js
This is the new OverconstrainedError in partial fulfillment of Issue #162 .  See closed PR #170 for discussion.
> Overconstrainederror

- getusermedia.html
> Specify order of add/removetrack and active/inactive events (issue #201)

- getusermedia.html
Solve the HTML5 validation failure in Travis CI; the respec errors are still to be fixed though.
> markup fixes

- getusermedia.html
> correct errors in overconstrained event definition

- getusermedia.html
From discussion in https://github.com/w3c/mediacapture-main/pull/216. I don't have any better ideas than this.
> typedef MediaStreamError as an object

- getusermedia.html
This is the text Jan-Ivar suggested in Issue #225.
> minor rewording in section 5

- getusermedia.html
Intended to fix https://github.com/w3c/mediacapture-main/issues/222
> specify that groupId is origin-unique

- getusermedia.html
> Use reference to WebIDL-1

- getusermedia.html
Missing definifion of DOMException
Invalid respec usage for typedef
> Fix markup errors

- getusermedia.html
close #255
from @alvestrand proposed text
> Warn against UUID fingerprinting

- getusermedia.html
Applying minor wording change resulting from issue #237 discussion.
> fix trackClone algorithm wording

- getusermedia.html
> Update privacy section with lessons from TAG questionnaire

- getusermedia.html
> Clarify how a cloned track is initialized (remove 'inherit' language) (Issue  #232)

- .travis.yml
- W3CTRMANIFEST
- getusermedia.html
see https://lists.w3.org/Archives/Public/public-webrtc-editors/2015Nov/0006.html
> Use new Travis CI set up

- getusermedia.html
Fix for:
https://github.com/w3c/mediacapture-main/issues/242
https://github.com/w3c/mediacapture-main/issues/249
https://github.com/w3c/mediacapture-main/issues/250
> Add detailed steps for removeTrack() and fix a security considerations issue.

- getusermedia.html
https://github.com/w3c/mediacapture-main/issues/250
> Fix for Issue 250 Security-Arch reference for MUST

- getusermedia.html
removeTrack() currently redefines the procedure.
> Let removeTrack() reference the 'remove a track' steps

- getusermedia.html
> Clarify equality for string constraints

- getusermedia.html
> Remove outdated paragraph on constraints in tracks

- getusermedia.html
Proposed patch for the resolution in [1].
Removed events
Updated examples
[1] https://lists.w3.org/Archives/Public/public-media-capture/2015Nov/0012.html
> Remove MediaStream active/inactive events (fixes: #283)

- getusermedia.html
> Clarify that constraint in overconstrainederror is defined in selectsettings

- getusermedia.html
This is the PR for issue #244.
> New extension section

- getusermedia.html
> getSupportedConstraints(): Remove prose about dictionary member default values (fixes: #293)

- getusermedia.html
This PR proposes text to explain the WebIDL limitation for ConstrainablePattern (see issue #288).
> Explain WebIDL limitation for ConstrainablePattern

- getusermedia.html
The title says it all.  This is an attempt to address issue #246.
> Clarify how the generic applyConstraints algorithm applies to MSTs

- getusermedia.html
> Use NotAllowedError for permission failure in getUserMedia algorithm (issue #317)

- getusermedia.html
> Clarify that group ID is non-persistent

- getusermedia.html
My interpretation of what the discussion of #333 seems to lead to.
close #333
> Restrict emission of devicechange event to apps with list-devices perm

- getusermedia.html
> Issue 316:  add links to constrainable properties

- getusermedia.html
> Make ended event a simple event

- getusermedia.html
> Various fixes to permission language

- getusermedia.html
Proposed fix for #346 .
Close #346
> Removes sourceType from the document.

- getusermedia.html
> Be specific on what live tracks grant implicit permission.

- getusermedia.html
> Remove 'User Media in an IFrame' section and use new 'user media enabled flag'

- getusermedia.html
see https://lists.w3.org/Archives/Public/public-webrtc/2016May/0073.html
Here is [an imperfect diff of before/after of the generated documents](http://services.w3.org/htmldiff?doc1=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttp%3A%2F%2Frawgit.com%2Fw3c%2Fmediacapture-main%2Fmaster%2Fgetusermedia.html&doc2=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttp%3A%2F%2Frawgit.com%2Fw3c%2Fmediacapture-main%2Fcontiguous%2Fgetusermedia.html)
> Convert to WebIDL contiguous mode in ReSpec

- getusermedia.html
Rebase of https://github.com/w3c/mediacapture-main/pull/373. Issue https://github.com/w3c/mediacapture-main/issues/359.
> Add pre-grant deviceId alternative (Rebased).

- getusermedia.html
> Make constraints webidl optional in gUM call and add explanatory prose

- getusermedia.html
> Add room fingerprinting to security considerations

- getusermedia.html
> Fix links to MediaStream's methods

- getusermedia.html
It might be easier to read the spec with less jumping around if we unroll these short algorithms.
Proposed fix for issue #388
> Editorial: Unroll add and remove track steps

- getusermedia.html
> Made removal of device(s) fire devicechange event.

- getusermedia.html
Fix for https://github.com/w3c/mediacapture-main/pull/411 based on @burnburn's pr. PTAL.
> Add Privacy Indicator Requirements

- Makefile
I suspect I am the only person who uses this so risk of breaking stuff seems fairly low....
> Name of html2text.py has changed

- getusermedia.html
> Allow getConstraints to return semantically equivalent constraint object

- getusermedia.html
Also moves the paragraph containing this change earlier in the doc so it's easier to find.
Fix for issue #394 .
> Require all constraints to be satisfied when settings are changed

- getusermedia.html
Fix for https://github.com/w3c/mediacapture-main/issues/414.
> Clarify when and where devicechange events fire.

- getusermedia.html
and other new warnings recently raised by ReSpec
close #435
> Fix ReSpec warnings for WebIDL interfaces

- getusermedia.html
Defines the "applyConstraints algorithm" separately from the
applyConstraints function, and links to algorithm in getUserMedia calls.
Fixes #386
> Specify the "applyConstraints algorithm" more clearly

- getusermedia.html
Fixes Issue #429 as Harald suggested there.
> Specify that getSettings omits non-applicable settings

- getusermedia.html
Add informative section for guidance when creating new consumers.  To address issue #400.
> add guidance for new consumers

- getusermedia.html
> Specify how applyConstraints() should behave without the argument

- getusermedia.html
Fix for https://github.com/w3c/mediacapture-main/issues/444.
> Add autoGainControl and noiseSuppression.

- getusermedia.html
Fixes #448 
Adds informative reference to "Media Capture from DOM Elements" spec
> Add text about alternative ways to obtain local media

- getusermedia.html
> Add track to stream's track set only when constructor's argument is present

- getusermedia.js
See also https://github.com/w3c/respec/issues/1372
> Use post-processing to remove unwanted links to HTMLLS

- getusermedia.html
> Add missing [Exposed] extended attribute on InputDeviceInfo

- getusermedia.html
> Move originIdentifier out of in-parallel steps.

- getusermedia.html
Fix for https://github.com/w3c/mediacapture-main/issues/487.
> Fix permission-to-use link and language.

- getusermedia.js
@jan-ivar, can you confirm your w3cid?
> Editorial: Add jib as editor

- getusermedia.html
Partial fix for https://github.com/w3c/webrtc-pc/issues/1599.
> Add synchronous addtrack and removetrack algorithms.

- getusermedia.html
Fix for https://github.com/w3c/mediacapture-main/issues/466.
> Make different settings values per track possible.

- getusermedia.html
Fix for https://github.com/w3c/mediacapture-main/issues/530.
> Move applyConstraints algorithm off main thread, and handle errors.

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/pull/558. @alvestrand @henbos PTAL.
[Preview](https://rawgit.com/w3c/mediacapture-main/5fa79d737369b892e981e5ffddac7e0ab20e9dbd/getusermedia.html#dfn-required-constraints)
> Define the three collective forms of constraints, to clarify prose (Editorial).

- getusermedia.html
See https://github.com/heycam/webidl/pull/609#issuecomment-463831882. @foolip
> exclude ConstrainablePattern from reffy.

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/549.
> Filter enumerateDevices by feature policy.

- getusermedia.html
> Clarify crop-and-scale

- getusermedia.html
Replace references of MediaDeviceInfo dictionary" by "MediaDeviceInfo object".
> Deep clone storedDeviceList in enumerateDevices

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/556.
> Move request permission steps into the for-loop.

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/648.
> Mandate proper permission disclosure.

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/482.
> Add [[Capabilities]], [[Constraints]] & [[Settings]] internal slots.

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/683
> Update the description of the DeviceInfo Access model given tigthening made to enumerateDevices

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/688.
> Clear [[storedDeviceList]] on setting [[canExposeDeviceInfo]] to true

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/670.
> Mention closing a laptop lid w/camera as a mute reason.

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/668.
> Add best practice on device muting.

- getusermedia.html
Clarify https://github.com/w3c/mediacapture-main/issues/640
> Clarify label may have no identifying info.

- getusermedia.html
> Fix definitions ReSpec no longer finds

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/709
> Make it clear that User Agent can use another track in the allowed track set if some of the tracks fail.

- getusermedia.html
Loop through discovered devices first to build a microphone list.
Loop through discovered devices second to build a camera list.
Append microphone list then camera list to resultList.
Then use exposure decision algorithm for other devices with microphone list and camera list as input.
> Pass camera and microphone lists to the exposure decision algorithm

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/748.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/750.html" title="Last updated on Nov 18, 2020, 6:41 PM UTC (3c20237)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/750/fc47ff4...jan-ivar:3c20237.html" title="Last updated on Nov 18, 2020, 6:41 PM UTC (3c20237)">Diff</a>
> s/current settings object/relevant settings object/

- getusermedia.html
close #634
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/751.html" title="Last updated on Nov 20, 2020, 7:28 AM UTC (e9b19a4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/751/6713be6...e9b19a4.html" title="Last updated on Nov 20, 2020, 7:28 AM UTC (e9b19a4)">Diff</a>
> Align terminology to User Agent

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/747
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/759.html" title="Last updated on Dec 17, 2020, 3:52 PM UTC (c7525fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/759/826b76a...youennf:c7525fa.html" title="Last updated on Dec 17, 2020, 3:52 PM UTC (c7525fa)">Diff</a>
> Mention that device labels can be sanitized

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/660.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/760.html" title="Last updated on Dec 17, 2020, 4:03 PM UTC (6c12505)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/760/826b76a...jan-ivar:6c12505.html" title="Last updated on Dec 17, 2020, 4:03 PM UTC (6c12505)">Diff</a>
> Define behavior when rotating camera.

- getusermedia.js
Fixes https://lists.w3.org/Archives/Public/public-webrtc/2021Jan/0015.html
> Add Youenn Fablet to the list of editors.

- getusermedia.html
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/772.html" title="Last updated on Feb 18, 2021, 3:22 PM UTC (366e88d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/772/0314705...jan-ivar:366e88d.html" title="Last updated on Feb 18, 2021, 3:22 PM UTC (366e88d)">Diff</a>
> Improve examples (limit use of getSupportedConstraints() to where needed)

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/777
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/783.html" title="Last updated on Apr 8, 2021, 2:26 PM UTC (c344b8e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/783/aca31f1...youennf:c344b8e.html" title="Last updated on Apr 8, 2021, 2:26 PM UTC (c344b8e)">Diff</a>
> Provide guidelines for getUserMedia default values

- getusermedia.html
Needed  by https://github.com/w3c/permissions/pull/225
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/790.html" title="Last updated on May 24, 2021, 7:26 AM UTC (07dacef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/790/ddc3ac0...07dacef.html" title="Last updated on May 24, 2021, 7:26 AM UTC (07dacef)">Diff</a>
> chore: export 'device permission revocation algorithm'

- getusermedia.html
Closes #791
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/793.html" title="Last updated on May 28, 2021, 4:11 AM UTC (856831c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/793/ddc3ac0...856831c.html" title="Last updated on May 28, 2021, 4:11 AM UTC (856831c)">Diff</a>
> Chore: don't redefine Navigator

- getusermedia.html
These were was pointing to wrong defs...
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/797.html" title="Last updated on Jun 10, 2021, 9:11 AM UTC (a9cd2b3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/797/c211631...a9cd2b3.html" title="Last updated on Jun 10, 2021, 9:11 AM UTC (a9cd2b3)">Diff</a>
> Editorial: remove/link dependencies

- getusermedia.html
***
<a href="https://pr-preview.s3.amazonaws.com/eladalon1983/mediacapture-main/pull/840.html" title="Last updated on Dec 14, 2021, 5:39 PM UTC (4896426)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/840/6bdaf30...eladalon1983:4896426.html" title="Last updated on Dec 14, 2021, 5:39 PM UTC (4896426)">Diff</a>
> Fix up language around `muted`

- getusermedia.html
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/839.html" title="Last updated on Dec 9, 2021, 6:25 PM UTC (258b965)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/839/6bdaf30...jan-ivar:258b965.html" title="Last updated on Dec 9, 2021, 6:25 PM UTC (258b965)">Diff</a>
> Missed a couple of s/track/candidate/ in #833.

- getusermedia.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/884.html" title="Last updated on Jun 7, 2022, 6:12 PM UTC (68eb028)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/884/077f884...68eb028.html" title="Last updated on Jun 7, 2022, 6:12 PM UTC (68eb028)">Diff</a>
> Improve markup for event tables

- getusermedia.html
and add an id to make it linkable.
editorial
***
<a href="https://pr-preview.s3.amazonaws.com/fippo/mediacapture-main/pull/926.html" title="Last updated on Jan 31, 2023, 9:09 AM UTC (044bfdc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/926/6a3eaf2...fippo:044bfdc.html" title="Last updated on Jan 31, 2023, 9:09 AM UTC (044bfdc)">Diff</a>
> Split device sanitation note into separate paragraph

- getusermedia.html
Fixes #927.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/932.html" title="Last updated on Feb 23, 2023, 3:23 PM UTC (7761889)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/932/b539fcd...jan-ivar:7761889.html" title="Last updated on Feb 23, 2023, 3:23 PM UTC (7761889)">Diff</a>
> query without deviceId is for access to any device of a kind.

- getusermedia.html
- getusermedia.js
See preview.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/964.html" title="Last updated on Jul 11, 2023, 8:56 PM UTC (8212e08)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/964/76a2643...jan-ivar:8212e08.html" title="Last updated on Jul 11, 2023, 8:56 PM UTC (8212e08)">Diff</a>
> Add caniuse link.

- getusermedia.html
Fixes #966. For discussion.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/1007.html" title="Last updated on Jun 20, 2024, 1:33 PM UTC (898177b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/1007/cec8e2a...jan-ivar:898177b.html" title="Last updated on Jun 20, 2024, 1:33 PM UTC (898177b)">Diff</a>
> Add userInsertedDevices attribute to DeviceChangeEvent

- getusermedia.html
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/1010.html" title="Last updated on Jun 27, 2024, 2:43 PM UTC (2be56ad)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/1010/23d5d73...youennf:2be56ad.html" title="Last updated on Jun 27, 2024, 2:43 PM UTC (2be56ad)">Diff</a>
> Export the allowed required constraints for device selection definition

- getusermedia.html
Fixes #1027.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/1032.html" title="Last updated on Feb 26, 2025, 10:42 PM UTC (340502c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/1032/b2054ef...jan-ivar:340502c.html" title="Last updated on Feb 26, 2025, 10:42 PM UTC (340502c)">Diff</a>
> Remove statement that Source capabilities are constant

- getusermedia.html
Fixes https://github.com/w3c/mediacapture-main/issues/1029
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/1037.html" title="Last updated on Apr 24, 2025, 2:13 PM UTC (d54c50c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/1037/4d96849...youennf:d54c50c.html" title="Last updated on Apr 24, 2025, 2:13 PM UTC (d54c50c)">Diff</a>
> Add a note stating that the UA will delay changing the device settings when track gets unmuted
