getusermedia.html

Remove redundant steps in advanced algorithm, and clarify that fitness distance from this step is not used later.
Also, replace "SHOULD use the one with a smaller fitness distance" - because there's generally no stand-out small one - with "SHOULD use the one with the smallest fitness distance", the likely meaning. The alternative interpretation would be "SHOULD use one with a smaller fitness distance", both mild suggestions of varying precision.

Fix language around advanced algorithm to be unambiguous.

---

getusermedia.html

("browsing session" is already used e.g. in geo, powerful-features)

using "browsing session" instead of "session"

---

getusermedia.html

Fixes internal references to MediaStream.addTrack() and MediaStreamTrack.clone().

Refer to interal algorithms instead of API layer methods (Issue #158)

---

getusermedia.html

Partially fulfills #162. See also #170.

Change NotFoundError from a MediaStreamError to a DOMException

---

getusermedia.html

Partially fulfills #162.  See also #170.

Change NotSupportedError from a MediaStreamError to a DOMException

---

getusermedia.html

We should not have any text in the event handler attribute descriptions saying that this event handler is fired when this or that happens. The event handler attributes are fired as part of the event flow procedure and that's redundant to describe for every single attribute handler.
This PR simplifies the event handler attribute descriptions to only mention the corresponding event type (that links to the event summary table).

Remove text about firing event handlers (from event handler attribute descriptions)

---

getusermedia.html

It appears that the rewrite of the gUM algorithm to use SelectSettings inadvertently changed some of the errors.  Specifically, the NotFoundError should have been for the case where no suitable sources were available even before applying constraints, and the ConstraintNotSatisfiedError should have been used for the case where no suitable sources were found after applying constraints, meaning that at least one required constraint could not be satisfied.

Fix Not Found Error in gUM algorithm

---

getusermedia.html

Now that PR #194 has landed, this request updates the interface to be used to throw the OverconstrainedError as an event.

MediaStreamErrorEvent -> OverconstrainedErrorEvent

---

getusermedia.html

LC proposal documented in https://lists.w3.org/Archives/Public/public-media-capture/2015Jun/0031.html to address lack of channel count information in audio track capabilities.

Add channelCount to audio track settings, constraints, capabilities

---

getusermedia.html

The [spec says](http://w3c.github.io/mediacapture-main/getusermedia.html#widl-MediaDevices-getSupportedConstraints-MediaTrackSupportedConstraints):
"A supported constrainable property MUST be represented by a member whose name is the constraint name and *whose value is true*. Any constrainable properties not supported by the User Agent MUST *not be present* in the returned dictionary."
In other words, members are always true. This optimizes the WebIDL to match.
I was originally against the breakdown of discrete dictionaries here, because of the code maintenance burden (more places to forget to update for each new constraint implemented), but I like that this at least can be managed entirely in the WebIDL definition file (and WebIDL binding code) without needing to define members *and* …

Once you implement a MediaTrackSupportedConstraints member, you support it

---

getusermedia.html

Now that updates to the error names have been completed, can we just remove all the ones from this table that are actually DOMExceptions?

remove DOMExceptions from error names table

---

getusermedia.html

Also moved bullet where p, the promise, is created to align with style in Promise Guide.

Issue #189: getUserMedia: Reject with TypeError if no media types are given

---

getusermedia.html

```
0:17.87 WebIDL.WebIDLError: error: Dictionary argument or union argument containing a dictionary not followed by a required argument must be optional, /Users/Jan/moz/mozilla-central/dom/webidl/MediaStreamTrack.webidl line 75:67
0:17.87     Promise<void>          applyConstraints (MediaTrackConstraints constraints);
0:17.87                                                                    ^
```
From https://heycam.github.io/webidl/#idl-operations
"If the type of an argument is a dictionary type or a union type that has a dictionary type as one of its flattened member types, and that dictionary type and its ancestors have no required members, and the argument is either the final argument or is followed only by optional arguments, then the argument MUST be specified as optional. Such …

make applyConstraints arg optional to fix webidl error

---

getusermedia.html

We set up the variable *candidates* but then never use it in the returned result. Made it explicit. Also, we return from "function" in one place and from "algorithm" in the other. Made it consistent.

fix unused candidates in SelectSettings, and consistent language around return.

---

getusermedia.html

LC proposal documented in https://lists.w3.org/Archives/Public/public-media-capture/2015Jun/0034.html to allow applications to discover device capabilities.

Allow device capabilities to be discoverable via enumerateDevices

---

getusermedia.html

Fixed for MediaStream and MediaStreamTrack

Remove static like definitions of attributes and methods

---

getusermedia.html

To address issue #227.   The changes are split into two commits -- the first makes wording changes, and the second merely moves the new text to a new location.

Align onoverconstrained

---

getusermedia.html

Remove IANA registry
Move definitions of MediaStreamTrack constrainable properties to subsection of MediaStreamTrack section
Remove references to registered values and instead make references to properties

Reorganize definition of constrainable properties without a registry

---

getusermedia.html

The steps never bail after rejecting the promise, causing *newConstraints* to be applied regardless of failure. I also removed the use of the undefined *existingConstraints* variable.

Fix applyConstraints steps to avoid unused var and bail on reject. 

---

getusermedia.html

https://github.com/w3c/mediacapture-main/issues/193
In addition to adding text to illustrate frameRate constraints, this PR ensures correct spelling of "frameRate" throughout the document.

Fix for Issue 193 Adaptive frame rate

---

getusermedia.html

The new steps references the general steps for adding/removing tracks.
Also moved text about this specification not defining any UA stream updates from the event section to the new section describing the behaviour.

Add text about User Agent stream updates (fixes #276)

---

getusermedia.html

The dictionary member is a DOMString [1]
https://w3c.github.io/mediacapture-main/#media-track-capabilities

Fix facingMode in Capabilities example

---

.travis.yml
getusermedia.html

When this is merged, Travis CI will complain on pull requests that aren't line-wrapped at 80 characters.
To do proper line-wrapping, this idea is to:
* commit your changes without line-wrap
* rewrap the content using webrtc-respec-ci/Makefile with `make linewrap LINEWRAPLENGTH=80`
* do a commit for the linewrap

Reformat with enforced line wrap at 80

---

getusermedia.html

Lots of links so here's a rendered preview (find changes about a page down):
https://rawgit.com/adam-be/mediacapture-main/double-keying/getusermedia.html#widl-MediaDevices-getUserMedia-Promise-MediaStream--MediaStreamConstraints-constraints

Specify permission model for nested browsing contexts (fixes: #267)

---

getusermedia.html

Related: PR #307, Issue #296
In this PR I've tried to sort out some of the problems we've talked about so far related to Capabilites:
Capabilites section in the (General) Constrainable Pattern section:
- Removed use of "supported"
- Use "constrainable object" instead of User Agent when referring to the entity that has capabilites. (Also added a definition of "constrainable object")
MediaStreamTrack section:
- Add text saying that it's a constrainable object
- Add note in getCapabilites() that it's the source that provides capabilites
MediaTrackCapabilites section:
- Use source instead of User Agent.
Preview: http://rawgit.com/adam-be/mediacapture-main/sort-out-capabilites/getusermedia.html#idl-def-Capabilities

Clarify how Capabilites should work

---

getusermedia.html

This is text for review. ReSpec complains about one error still, but I can't see it.
Fixes #305

Text incorporating the Permissions API's definition of permission handling

---

getusermedia.html

Fix for issue #339
First commit is purely editorial so please review the second.

Use 'originIdentifier' in getUserMedia() steps (issue #339)

---

getusermedia.html

Closes #352
Diff also moves the "overconstrained" call-out, since the loop can now exit either with "overconstrained" or with "permission denied".

Getusermedia: Pull the permissions check into the per-type loop

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/375.

Allow firing devicechange just once when inserting a camera with mic.

---

getusermedia.html

Rebase of https://github.com/w3c/mediacapture-main/pull/377.

JS should see devicechange events during active gum call (rebased).

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/387 as discussed at TPAC.
I've updated the text from the TPAC slides based on feedback, including:
- Use maps instead of dynamically composed internal slot names.
- Reduce logic to boolean states and drop increment counters.
- Make clear permissions apply only to sources exposed by getUserMedia.
- Remove the option to set device accessible indicator differently depending on muting strategy.
@burnburn PTAL.

Define indicator states.

---

getusermedia.html

This should be all that's needed in the mediacapture spec for https://github.com/w3c/mediacapture-main/issues/380. The remaining changes are in https://github.com/w3c/permissions/pull/131.

Rename list-devices permission to device-info to match permission spec.

---

getusermedia.html

This is for issue #402, includes all changes in PR #407.  I'll close #407 separately.

Rules for when devicechange events may fire

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/408.

Remove unions in MediaTrackCapabilities (#408).

---

getusermedia.html

Fixes #390 
@alvestrand Here's the simplest change that fixes the problem. Changing Conformance to say Best Practices are non-normative would work too, but takes more drafting.

Mark the Implementation Suggestions as non-normative.

---

getusermedia.html

Updating text on whether context object is allowed to request access.

---

getusermedia.html

Ideal values (like height for an audio device) should be ignored
when calculating fitness distance. They still matter when exact.
Closes #409

Ignore ideal values that don't belong on the device

---

getusermedia.html

The term "optional" for constraints is outdated.  This PR cleans that up.  Addresses issue #396.

Remove outdated contraints text

---

getusermedia.html

allows MediaStreams to be created with a specific id, similar
to how it can be done for a MediaStreamTrack.
fixes https://github.com/w3c/webrtc-pc/issues/1196
Text is taken from https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-id with "MediaStreamTrack" replaced by "MediaStream" and "track id" by "stream id"

MediaStream: allow construction with given id

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/458.

Revert pull #446.

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/454.

Rename 10.1. to Legacy Interface Extensions.

---

getusermedia.html

These were inherited from the previous respec WebIDL format, but they now represent a maintenance footgun
See also https://github.com/w3c/webrtc-pc/pull/1450

Remove duplicate info on method parameters

---

getusermedia.html

Old sentence. Tracks, not streams, end now.

s/stream/track/ in section about ended event source.

---

getusermedia.html

Use new data-cite mechanism from respec to avoid outdated links
HTML5.2 now has 'allowed to use' definition, so using it instead of HTML LS
Remove note about referencing HTML5.1 for  as no longer relevant
Remove note about HTML Media Controllers (removed from HTML spec)

Upgrade our references to HTML5.2

---

getusermedia.html

Throw on getUserMedia in non-fully active documents.

---

getusermedia.html

cleanup code example in HTML help us understand features more easily.
so I cleanup some code like below.
- format indent
- use basic new feature of ES6^
- const
- arrow function
- async/await
- remove deprecated scoped css
- remove js from html
- simplify but save meaning and semantics
if there are some format rule or feature regulation in spec.
please mention me and I'll fix them.

format & fixup Example code

---

getusermedia.html

Partial fix for https://github.com/w3c/webrtc-pc/issues/1568.

Split out algorithm to set a track's muted state from other specs (editorial).

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/472.
Adds Peter's [TPAC proposal](https://docs.google.com/presentation/d/1Sg_1TVCcKJvZ8Egz5oa0CP01TC2rNdv9HVu7W38Y4zA/edit?ts=59f90fe9#slide=id.g2a6f3cad35_11_0), except for `"box-and-scale"` because it adds pixels, and is incompatible with the constraints algorithm (these fitness distances would compete with `"crop-and-scale"` and `"none"` modes, with unpredictable and undesirable results).

Add resizeMode constraint.

---

getusermedia.html

MediaDevices' `<dfn>` needs a `data-dfn-for=""` to distinguish it from the `mediaDevices` attribute

Fix compat with ReSpec19

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/459.

Make track.stop() idempotent.

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/470, given https://github.com/w3c/mediacapture-main/issues/466#issuecomment-351747593.

Clarify getSettings() are target values.

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/525. @bzbarsky PTAL.

Clarify+make fitness distance algorithm agnostic to dictionary member presence.

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/520.

New audible corollary to active stream property, to end audio elements

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/534.

Limit gUM permission exemption to when there are non-isolated live tracks.

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/538.

Have getCapabilities() return an empty dictionary instead of null

---

getusermedia.html

Fixes #533.
Some of the constrainable properties are said to be "defined to apply only to [video/audio] MediaStreamTrack objects". It is not clear whether specifying a constraint that doesn't apply for the type (e.g. {audio:{exact:640}}) would cause an OverconstrainedError or simply be ignored. Both are valid interpretations.
This PR says to ignore such constraints, because...
- This is what current implementations do.
- This requires less code to be updated when new constraints are added.
- If a constraint is not recognized by a User Agent it is ignored (because constraints are passed as dictionaries, anything not in the IDL would be ignored); this is consistent with "constraint is not implemented for this type".
- This would allow editorial changes such as splitting audio and video …

Clarify what happens to non-applicable constraints.

---

getusermedia.html

…and refer to official playback position rather than current stream position.
Fix for https://github.com/w3c/mediacapture-main/issues/543.

Remove InvalidStateError on setting currentTime

---

getusermedia.html

... the `allow='camera;microphone'` check now implicit in the permissions spec, now that https://github.com/w3c/permissions/pull/163 has merged.
For review, ~note that~ https://w3c.github.io/permissions/#reading-current-states ~does not yet reflect github tip for some reason, so please see the merged PR's [preview](https://pr-preview.s3.amazonaws.com/raymeskhoury/permissions/pull/163.html#reading-current-states) for the new language there relevant to this PR.~
Fixes https://github.com/w3c/mediacapture-main/issues/434 and https://github.com/w3c/mediacapture-main/issues/545.

Remove allowusermedia SecurityError check, in favor of allow=

---

getusermedia.html

Fix for https://github.com/w3c/mediacapture-main/issues/545.

Define "camera" and "microphone" feature policies.

---

getusermedia.html

This is an editorial fix.
The intent here was always to exclude background tabs, yet this check did not accomplish that: Checking whether a browsing context's *"active document* is *"fully active"* is circular and almost always true, except for some iframes.

Fix nonsense s/active document/responsible document/ in devicechange (editorial)

---

getusermedia.html

Make MediaDeviceInfo interface [SecureContext] also.

---

getusermedia.html

Introduce a device information exposure check routine that does the checks previously defined to fire the devicechange event.
Use that routine for devicechange event.
Use that routine to postpone getUserMedia and enumerateDevices steps until this routine returns true.
Sanitize constraint error if device info permission is granted.

Mitigate getUserMedia/enumerateDevices fingerprinting issues based on device info permission

---

getusermedia.js

It is my understanding that henbos is part of the editors for
mediastream-main but not listed among the editors. This commits fixes
that.

Add Henrik Boström to the list of editors.

---

getusermedia.html

Fixes #585
In #585 the WG has expressed interest in removing the volume constraint
from the specifications. This commit addresses the issue by removing the
definition of 'volume' together with the related references.

Remove the 'volume' constraint.

---

getusermedia.html

Make it clear groupId is per browsing context.
Refactor to have the groupId constraint refer to MediaDeviceInfo.groupId definition.

Clarify groupId persistency

---

images/change_states_before.svg

Fix #547
Fix the reported typo in https://www.w3.org/TR/mediacapture-streams/#the-model-sources-sinks-constraints-and-settings
where one of the sinks is incorrectly named 'X' instead of 'Y'. This
commit fixes the typo in the SVG image, so to be consistent with the
rest of the text and the other illustration.

Fix typo in sink label.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/599.

Clarify language around element attributes after stream removal.

---

getusermedia.html

The algorithm for ending tracks for reasons other than stop() doesn't
have a definition. Having one lets us reference it from this and other
specifications.
This helps w3c/mediacapture-fromelement#81.

Add definition to track-ending algorithm

---

getusermedia.html

Refactor to have the deviceId constraint description refer to MediaDeviceInfo.deviceId description.
Update the description so that deviceId constraint refers to a device and not a source of the content.
Web audio track and canvas track definitions should probably make it clear that deviceId is not meaningful there.

Unify device id description

---

getusermedia.html

Also refactor to make reference from deviceId/groupId constraints to MediaDeviceInfo attribute fields.
Clarify groupId lifetime.
Make reference to rfc4122 for deviceId.

Clarify that some device ids may not be origin-unique

---

getusermedia.html

Follows https://github.com/w3c/webrtc-pc/pull/2232.

Fix inconsistent WebIDL. Reformat to follow de facto code style of WebIDL,HTML,DOM. (editorial)

---

getusermedia.html

PR for https://github.com/w3c/mediacapture-main/issues/604.
This hopefully makes it clear that a groupId is stable for the lifetime of a document.
Previously, if a device groupId was not in oldList/resultList, it would need to be regenerated.

Remove oldList and make it clear that groupId scope is the document

---

getusermedia.html

Also mention change of default device for devicechange event

Update enumerateDevices to list default capture devices as first.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/615.

Use HTMLMediaElement's potentially playing definition.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/518.
[Preview](https://rawgit.com/w3c/mediacapture-main/98588c04c0c76aeabbd0cd9a690ae594a3ba7c57/getusermedia.html#mediastreams-in-media-elements)

Use HTMLMediaElement's ended playback definition.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/635.
Editorial PR.

Normalize style of methods. Remove '()' from the names on all methods.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/642.

Relinquish device when all tracks are muted or disabled.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/598. @annevk PTAL.

Have deviceId follow partitioning rules for storage (such as localStorage)

---

getusermedia.html
getusermedia.js

Use respec autolinks as much as possible
align with latest terminology of Permission API
fix a couple of bugs in the process
align references and their statuses with reality (mediarecorder, imagecapture, webrtc, and webaudio aren't normative references)

Use more consistent linking practices

---

getusermedia.html

Spec now fully owned by WebRTC
Also, point to github repo rather than mailing list

Remove outdated mentions of Media Capture Task Force

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/682.

Remove UUID recommendation for deviceId and groupId.

---

getusermedia.html

The algorithm makes things easier to read.
It might be also used by mediacapture-output.
The filtering is done specifically for cameras and microphones but is let unspecified for speakers, the idea being that mediacapture-output will define how devices get exposed (ideally through an Api to request access to specific speaker, alternatively when a speaker device is already exposed as it is grouped with an exposed camera/microphone device)

Introduce a new algorithm to create a new MediaDeviceInfo

---

getusermedia.html

This PR simply fixes the link to `toJSON()` in MediaDeviceInfo as it has been renamed [recently](https://github.com/w3c/respec/pull/2875/).

Fix link for toJSON() in MediaDeviceInfo

---

getusermedia.html

This introduces a hook so that other specifications can define the exact exposure algorithm.

Extend enumerateDevices algorithm to handle non camera and microphone devices

---

getusermedia.html

This CL defines the fitness distance also for required constrains whose
value contains a member named 'ideal' in addition to members named
'exact', 'max' and/or 'min'.
Lets take a **width** constraint `{ideal: 1920, min: 320}` as an example and lets assume that the browser supports the constraint and that there are settings dictionaries which satisfy the constraint (so fitness distance algorithm steps 1 and 2 can be ignores).
Then,
* the step 3 does not apply because the constraint is required (has 'min'),
* the step 4 does not apply because the ideal value is specified, and
* the steps 5 and 6 do not apply because the constraint is not non-required but required,
thus the fitness distance is undefined.
Clearly, the step 5 should apply and the fitness distance should be positive infinity …

Define the fitness distance for all required constrains.

---

getusermedia.html

In case an unallowed required constraint is given to getUserMedia, skip it.
This would help https://github.com/w3c/mediacapture-image/issues/229.

Identify the list of allowed required constraints for getUserMedia

---

getusermedia.html

A follow-up fix to a bug introduced by https://github.com/w3c/mediacapture-main/pull/717.

Reorder steps to not set privacy indicator for device that fails to open.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/724.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/734.html" title="Last updated on Nov 12, 2020, 3:23 PM UTC (8476eca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/734/ea45c6a...jan-ivar:8476eca.html" title="Last updated on Nov 12, 2020, 3:23 PM UTC (8476eca)">Diff</a>

Privacy indicator false-to-true transition SHOULD be 3 seconds.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/439 once I add a PR to permissions that invokes it.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/745.html" title="Last updated on Nov 4, 2020, 10:36 PM UTC (f2cf6e4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/745/87cb2f7...jan-ivar:f2cf6e4.html" title="Last updated on Nov 4, 2020, 10:36 PM UTC (f2cf6e4)">Diff</a>

Add permission revocation algorithm

---

getusermedia.html
getusermedia.js

Fixes https://github.com/w3c/mediacapture-main/issues/568.
I made the `constraint` argument always present and `""` in cases where the constraint name is either filtered out or undetermined. This matches Safari and Firefox at least (I wasn't able to provoke the absence of a constraint in Chrome).
I also fixed some bugs in the algorithms around `failedConstraint` in the process.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/746.html" title="Last updated on Nov 9, 2020, 11:23 PM UTC (61257f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/746/87cb2f7...jan-ivar:61257f4.html" title="Last updated on Nov 9, 2020, 11:23 PM UTC (61257f4)">Diff</a>

OverconstrainedError extends DOMException + algo fixes

---

.github/workflows/update-respec.yml

Cf https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Adapt GitHub CI to platform change

---

getusermedia.html

This also mandates min width, min height and min frame rate to be 1.
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/731.html" title="Last updated on Dec 3, 2020, 3:38 PM UTC (c1861fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/731/ea45c6a...youennf:c1861fd.html" title="Last updated on Dec 3, 2020, 3:38 PM UTC (c1861fd)">Diff</a>

Add requirements to support downsampling and frame decimation

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/756
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/757.html" title="Last updated on Dec 17, 2020, 9:38 AM UTC (8a2caca)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/757/826b76a...youennf:8a2caca.html" title="Last updated on Dec 17, 2020, 9:38 AM UTC (8a2caca)">Diff</a>

Make sure to have the default audio output device be the first device in enumerateDevices list that is not a microphone and not a camera

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/646
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/758.html" title="Last updated on Dec 17, 2020, 3:47 PM UTC (d9cb423)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/758/826b76a...youennf:d9cb423.html" title="Last updated on Dec 17, 2020, 3:47 PM UTC (d9cb423)">Diff</a>

Mention enumerateDevices fingerprinting mitigation pre-capture

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/729.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/768.html" title="Last updated on Jan 28, 2021, 3:31 PM UTC (08692dc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/768/5390462...jan-ivar:08692dc.html" title="Last updated on Jan 28, 2021, 3:31 PM UTC (08692dc)">Diff</a>

UA s/SHOULD/MUST/ use one with the smallest fitness distance

---

getusermedia.html

Replaces https://github.com/w3c/mediacapture-main/pull/742 as partial fix to https://github.com/w3c/mediacapture-image/issues/256.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/766.html" title="Last updated on Jan 19, 2021, 6:52 PM UTC (8f5f129)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/766/aa0eae1...jan-ivar:8f5f129.html" title="Last updated on Jan 19, 2021, 6:52 PM UTC (8f5f129)">Diff</a>

Fitness distance for bool placeholder & constraints not supported by device.

---

getusermedia.html

The Capabilities, Settings, Constraints and ConstraintSet dictionaries are not meant to be directly implemented - they document the Constrainable pattern.
To avoid having them be considered as part of the normative surface of the spec, they're marked-up with the example class - similar to what we do with ConstrainablePattern.
This in particular helps with automatically extracted IDL fragments as done by webref / reffy https://github.com/w3c/webref/
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/769.html" title="Last updated on Jan 29, 2021, 1:27 PM UTC (b348d7b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/769/6b782b5...b348d7b.html" title="Last updated on Jan 29, 2021, 1:27 PM UTC (b348d7b)">Diff</a>

Mark up IDL from constrainable patterns as non-normative

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/762.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/770.html" title="Last updated on Feb 4, 2021, 2:30 PM UTC (d9c7ad2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/770/6b782b5...jan-ivar:d9c7ad2.html" title="Last updated on Feb 4, 2021, 2:30 PM UTC (d9c7ad2)">Diff</a>

Have resizeMode: 'none' mean native frame rate as well.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/761.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/771.html" title="Last updated on Feb 4, 2021, 3:30 PM UTC (1437b8c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/771/6b782b5...jan-ivar:1437b8c.html" title="Last updated on Feb 4, 2021, 3:30 PM UTC (1437b8c)">Diff</a>

Add native res + decimated frameRate example, handling rotation.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/645
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/773.html" title="Last updated on Feb 18, 2021, 11:09 AM UTC (7936a9a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/773/f20117e...youennf:7936a9a.html" title="Last updated on Feb 18, 2021, 11:09 AM UTC (7936a9a)">Diff</a>

Add camera and microphone specific checks for device info exposure

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/800
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/801.html" title="Last updated on Jul 1, 2021, 6:51 AM UTC (8870e23)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/801/0b7cbc6...youennf:8870e23.html" title="Last updated on Jul 1, 2021, 6:51 AM UTC (8870e23)">Diff</a>

Expose explicitly granted output devices even if device enumeration is off

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/804
Change is consistent with existing browser behaviours which stop MediaStreamTracks when their context goes away.
We introduce a new slot shouldStopSource that will be used by mediacapture-extensions
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/805.html" title="Last updated on Aug 12, 2021, 3:15 PM UTC (2fdfd99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/805/417447b...youennf:2fdfd99.html" title="Last updated on Aug 12, 2021, 3:15 PM UTC (2fdfd99)">Diff</a>

Clarify that a source lifetime is bound to its context

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/809
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/815.html" title="Last updated on Aug 26, 2021, 4:27 PM UTC (d9d8ca3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/815/5614349...youennf:d9d8ca3.html" title="Last updated on Aug 26, 2021, 4:27 PM UTC (d9d8ca3)">Diff</a>

Audio output device default change should also trigger devicechange event

---

getusermedia.html

See also https://github.com/w3c/mediacapture-output/pull/128
***
<a href="https://pr-preview.s3.amazonaws.com/miketaylr/mediacapture-main/pull/829.html" title="Last updated on Nov 18, 2021, 10:49 PM UTC (4fe103a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/829/b87662a...miketaylr:4fe103a.html" title="Last updated on Nov 18, 2021, 10:49 PM UTC (4fe103a)">Diff</a>

Define "camera" and "microphone" powerful feature types and algorithms

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/812.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/822.html" title="Last updated on Dec 2, 2021, 8:54 PM UTC (893e1d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/822/371cccd...jan-ivar:893e1d7.html" title="Last updated on Dec 2, 2021, 8:54 PM UTC (893e1d7)">Diff</a>

Add internal slots to MediaStreamTrack.

---

getusermedia.html

***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/838.html" title="Last updated on Dec 9, 2021, 2:34 PM UTC (0b63702)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/838/5af9608...youennf:0b63702.html" title="Last updated on Dec 9, 2021, 2:34 PM UTC (0b63702)">Diff</a>

Mention mobile operating systems and add a requirement for User Agents to update muted when OS decides to mute/unmute

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/849
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/850.html" title="Last updated on Jan 10, 2022, 10:59 AM UTC (cd67bde)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/850/961f7e6...youennf:cd67bde.html" title="Last updated on Jan 10, 2022, 10:59 AM UTC (cd67bde)">Diff</a>

Filter getUserMedia errors if permission is denied

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/852
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/853.html" title="Last updated on Jan 14, 2022, 2:52 PM UTC (75a7d21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/853/961f7e6...youennf:75a7d21.html" title="Last updated on Jan 14, 2022, 2:52 PM UTC (75a7d21)">Diff</a>

Explicitly copy readyState when cloning a track

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/847
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/851.html" title="Last updated on Jan 10, 2022, 11:10 AM UTC (263d037)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/851/961f7e6...youennf:263d037.html" title="Last updated on Jan 10, 2022, 11:10 AM UTC (263d037)">Diff</a>

Check for permission policy synchronously when getUserMedia is called

---

getusermedia.html

Also, align other definitions with type / usage expectations to remove some of the lint warnings of respec (remaining ones depend on https://github.com/w3c/permissions/issues/369 and a respec bug)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/863.html" title="Last updated on Feb 25, 2022, 9:08 AM UTC (2bfebe8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/863/eb26b96...2bfebe8.html" title="Last updated on Feb 25, 2022, 9:08 AM UTC (2bfebe8)">Diff</a>

Fix markup for powerful features definition

---

getusermedia.html

closes https://github.com/w3c/respec/issues/4056
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/866.html" title="Last updated on Mar 7, 2022, 3:35 AM UTC (357cf19)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/866/2490d3f...357cf19.html" title="Last updated on Mar 7, 2022, 3:35 AM UTC (357cf19)">Diff</a>

Editorial: fix dual definition of permission strings

---

getusermedia.html

Depends on https://github.com/w3c/mediacapture-main/pull/867 (i.e., merge that one first 🙏)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/868.html" title="Last updated on Mar 7, 2022, 4:06 AM UTC (39d8dbc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/868/2490d3f...39d8dbc.html" title="Last updated on Mar 7, 2022, 4:06 AM UTC (39d8dbc)">Diff</a>

Editorial: slightly better use of ReSpec stuff

---

getusermedia.html

See error in https://w3c.github.io/mediacapture-extensions/.
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/877.html" title="Last updated on Apr 7, 2022, 2:42 PM UTC (c9821c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/877/0490a4e...youennf:c9821c4.html" title="Last updated on Apr 7, 2022, 2:42 PM UTC (c9821c4)">Diff</a>

Add back Initialize the underlying source algorithm as it is needed for transferring a MediaStreamTrack

---

getusermedia.html

close #871
Following model of https://github.com/w3c/mediacapture-screen-share/pull/210/files"
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/876.html" title="Last updated on Apr 25, 2022, 10:00 AM UTC (2ffc466)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/876/0490a4e...2ffc466.html" title="Last updated on Apr 25, 2022, 10:00 AM UTC (2ffc466)">Diff</a>

Replace usage of "responsible document"

---

getusermedia.html

see also https://github.com/w3c/media-source/issues/307#issuecomment-1110865467
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/878.html" title="Last updated on Apr 28, 2022, 1:22 PM UTC (5d5d99e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/878/d799253...5d5d99e.html" title="Last updated on Apr 28, 2022, 1:22 PM UTC (5d5d99e)">Diff</a>

Improve markup of enumeration tables

---

getusermedia.html

Follow-up to https://github.com/w3c/mediacapture-main/pull/876 — a platform object's [relevant global object](https://html.spec.whatwg.org/multipage/webappapis.html#concept-relevant-global) can be referenced directly.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/880.html" title="Last updated on May 3, 2022, 10:03 PM UTC (3f82c08)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/880/09ee520...jan-ivar:3f82c08.html" title="Last updated on May 3, 2022, 10:03 PM UTC (3f82c08)">Diff</a>

Reference relevant global object directly.

---

getusermedia.html

This allows to keep the specific type for cloning, as well as provide the hooks for specs to define initialisation of MediaStreamTrack subtypes in the specs defining the subtypes.
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/873.html" title="Last updated on Jun 16, 2022, 2:11 PM UTC (9ec2048)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/873/5f659a2...youennf:9ec2048.html" title="Last updated on Jun 16, 2022, 2:11 PM UTC (9ec2048)">Diff</a>

Add source specific handling for creation and cloning of tracks

---

getusermedia.html

A document is said to be capturing if one of its track source is a capture source and is live.
A capture source is created either by getUserMedia or getDisplayMedia.
Fixes https://github.com/w3c/mediacapture-main/issues/887
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/890.html" title="Last updated on Aug 18, 2022, 2:50 PM UTC (e86e63f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/890/7b093a3...youennf:e86e63f.html" title="Last updated on Aug 18, 2022, 2:50 PM UTC (e86e63f)">Diff</a>

Add an algorithm to determine whether a document is capturing or not.

---

getusermedia.html

Per [the WebIDL spec](https://webidl.spec.whatwg.org/#SecureContext), "An interface without the [SecureContext] extended attribute must not inherit from another interface that does specify [SecureContext]." Since `MediaDeviceInfo` has the `SecureContext` attribute, so must `InputDeviceInfo`.
***
<a href="https://pr-preview.s3.amazonaws.com/dogben/mediacapture-main/pull/901.html" title="Last updated on Sep 22, 2022, 2:09 PM UTC (68cdfeb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/901/e84ad3e...dogben:68cdfeb.html" title="Last updated on Sep 22, 2022, 2:09 PM UTC (68cdfeb)">Diff</a>

Add `SecureContext` attribute to `InputDeviceInfo`.

---

getusermedia.html

This ensures we do not get dummy similar audioinput or camera devices if only camera or only microphone is used.
Fixes https://github.com/w3c/mediacapture-main/issues/898
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/900.html" title="Last updated on Oct 6, 2022, 2:30 PM UTC (a8699aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/900/e84ad3e...youennf:a8699aa.html" title="Last updated on Oct 6, 2022, 2:30 PM UTC (a8699aa)">Diff</a>

Update enumerateDevices algorithm to make use of device-kind specific exposure checks when building cameraList and microphoneList.

---

getusermedia.html

Fixes #906.
***
<a href="https://pr-preview.s3.amazonaws.com/henbos/mediacapture-main/pull/908.html" title="Last updated on Oct 12, 2022, 10:44 AM UTC (435f338)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/908/e83b870...henbos:435f338.html" title="Last updated on Oct 12, 2022, 10:44 AM UTC (435f338)">Diff</a>

Clarify that frameRate as a setting is the configured value, not a measurement.

---

getusermedia.html

[aspectRatio](https://w3c.github.io/mediacapture-main/#dom-mediatrackcapabilities-aspectratio) has been a [DoubleRange](https://w3c.github.io/mediacapture-main/#dom-doublerange) since https://github.com/w3c/mediacapture-main/issues/408.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/916.html" title="Last updated on Nov 4, 2022, 2:32 PM UTC (04e33bd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/916/8248a8c...jan-ivar:04e33bd.html" title="Last updated on Nov 4, 2022, 2:32 PM UTC (04e33bd)">Diff</a>

Fix invalid capability in Example 12.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/752:
1. Relax document (iframe) focus to tlbc [system focus](https://html.spec.whatwg.org/multipage/interaction.html#tlbc-system-focus) (a step in the right direction)
2. Allow Safari prompts in foreground tabs, while maintaining focus requirement on allow, per https://github.com/w3c/mediacapture-main/issues/752#issuecomment-921352150
3. Remove focus requirement on enumerateDevices, per https://github.com/w3c/mediacapture-main/issues/752#issuecomment-1293797299
4. Fix race spotted in https://github.com/w3c/mediacapture-main/issues/905#issuecomment-1293812378 which prevented deterministic visibility-success checks:
```js
if (document.visibilityState == "visible") {
await navigator.mediaDevices.enumerateDevices(); // won't block on …
```

Allow gUM prompt ahead of focus + deterministic "visible" enumeration wo/focus

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/914.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/920.html" title="Last updated on Dec 15, 2022, 10:14 PM UTC (74e815e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/920/9d72c9e...74e815e.html" title="Last updated on Dec 15, 2022, 10:14 PM UTC (74e815e)">Diff</a>

Remove duplicate text

---

getusermedia.html

Update the non-normative [Privacy and Security Considerations](https://w3c.github.io/mediacapture-main/#privacy-and-security-considerations) section to reflect the normative algorithms after https://github.com/w3c/mediacapture-main/pull/574.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/897.html" title="Last updated on Dec 15, 2022, 10:07 PM UTC (b7ad1fd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/897/96e8f75...jan-ivar:b7ad1fd.html" title="Last updated on Dec 15, 2022, 10:07 PM UTC (b7ad1fd)">Diff</a>

Update Privacy and Security Considerations to reflect spec.

---

getusermedia.html

Fixes respec error.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/925.html" title="Last updated on Jan 12, 2023, 5:53 PM UTC (52fbe71)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/925/9a249e7...jan-ivar:52fbe71.html" title="Last updated on Jan 12, 2023, 5:53 PM UTC (52fbe71)">Diff</a>

Fix default allowlist link that broke.

---

getusermedia.html

Fixes #938. Using [hide whitespace](https://github.com/w3c/mediacapture-main/pull/939/files?diff=unified&w=1) when reviewing is recommended.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/939.html" title="Last updated on Mar 22, 2023, 8:26 PM UTC (6894336)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/939/92ea82d...jan-ivar:6894336.html" title="Last updated on Mar 22, 2023, 8:26 PM UTC (6894336)">Diff</a>

Move "global" internal slots to MediaDevices, and fix "relevant object" links

---

getusermedia.html

Fixes #944.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/947.html" title="Last updated on Mar 27, 2023, 3:48 PM UTC (de88099)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/947/bef7d32...jan-ivar:de88099.html" title="Last updated on Mar 27, 2023, 3:48 PM UTC (de88099)">Diff</a>

s/long/unsigned long/ in MediaTrackSettings.

---

getusermedia.html

Needed by https://github.com/w3c/mediacapture-output/pull/136.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/959.html" title="Last updated on May 4, 2023, 12:17 AM UTC (ab33394)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/959/0360058...jan-ivar:ab33394.html" title="Last updated on May 4, 2023, 12:17 AM UTC (ab33394)">Diff</a>

Add mediaDevices arg to [=exposure decision algorithm for devices other than camera and microphone=].

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/965.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/968.html" title="Last updated on Aug 17, 2023, 4:55 PM UTC (c7529b7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/968/76a2643...jan-ivar:c7529b7.html" title="Last updated on Aug 17, 2023, 4:55 PM UTC (c7529b7)">Diff</a>

Remove DevicePermissionDescriptor deviceId.

---

getusermedia.html

Fixes #941.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/942.html" title="Last updated on Sep 20, 2023, 9:11 PM UTC (f4e73c5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/942/582a0c2...jan-ivar:f4e73c5.html" title="Last updated on Sep 20, 2023, 9:11 PM UTC (f4e73c5)">Diff</a>

Add note about deviceId and groupId inconsistency with other capabilities.

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/584.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/971.html" title="Last updated on Sep 21, 2023, 6:07 PM UTC (eb4e0c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/971/6f3e93f...jan-ivar:eb4e0c8.html" title="Last updated on Sep 21, 2023, 6:07 PM UTC (eb4e0c8)">Diff</a>

Allow upscaling to conceal concurrent use.

---

getusermedia.html

This will prevent the WebIDL being extracted by reffy (and other tools) as part of the normative definition of the spec.
This will remove the (incorrect) subtests of https://wpt.fyi/results/mediacapture-streams/idlharness.https.window.html?run_id=5194214102532096&run_id=5194810834550784&run_id=5176276909817856 (e.g., `Navigator interface: operation getUserMedia(MediaStreamConstraints, NavigatorUserMediaSuccessCallback, NavigatorUserMediaErrorCallback)`), because these are not normatively part of the spec.
***
<a href="https://pr-preview.s3.amazonaws.com/gsnedders/mediacapture-main/pull/990.html" title="Last updated on Mar 4, 2024, 6:57 PM UTC (1960c81)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/990/da36d40...gsnedders:1960c81.html" title="Last …

Add class="informative" to "Legacy GetUserMedia interface" section

---

getusermedia.html

Fixes #972.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/996.html" title="Last updated on Apr 25, 2024, 2:34 PM UTC (7bec415)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/996/6a4eccb...jan-ivar:7bec415.html" title="Last updated on Apr 25, 2024, 2:34 PM UTC (7bec415)">Diff</a>

Add DeviceChangeEvent interface.

---

getusermedia.html

Step 1 to fixing #994, this is a pure reorder of the two subsections in [§ 4.3.1 Life-cycle and Media Flow](https://w3c.github.io/mediacapture-main/#life-cycle-and-media-flow), into `§ 4.3.1 Media Flow and Life-cycle`, for easier review.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/995.html" title="Last updated on Apr 25, 2024, 10:11 PM UTC (6cdb805)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/995/bf8dac0...jan-ivar:6cdb805.html" title="Last updated on Apr 25, 2024, 10:11 PM UTC (6cdb805)">Diff</a>

Reorder Media Flow and Life-cycle sections.

---

getusermedia.html

This PR is intended to fix a tiny typo introduced here: https://github.com/w3c/mediacapture-main/pull/996/files#diff-1217ca1c44ff30a33dd50c49d03b5cadc9633c789df8ff9370ed4a42859e1211R3468-R3470.
I guess it would also resolve #999.

Fix DeviceChangeEventInit WebIDL definition

---

getusermedia.html

Fixes #994 following a pure reorder in https://github.com/w3c/mediacapture-main/pull/995. Removes statements in § 4.3.1.2 already covered in § 4.3.1.1. PTAL
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/998.html" title="Last updated on May 17, 2024, 7:24 PM UTC (57650c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/998/248a96e...jan-ivar:57650c8.html" title="Last updated on May 17, 2024, 7:24 PM UTC (57650c8)">Diff</a>

Remove redundant statements about muted/enabled.

---

getusermedia.html

Define `MediaStreamTrack.[[Restrictable]]`, an internal slot that allows [Element Capture](https://screen-share.github.io/element-capture/) to differentiate between tracks that are valid target to `restrictTo()` and those which are not.
A respective PR will be produced on the [getViewportMedia](https://w3c.github.io/mediacapture-viewport/) spec, setting `[[Restrictable]]` to `true`.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/pull/1015.html" title="Last updated on Sep 26, 2024, 9:44 PM UTC (fe2fc77)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/1015/48b8708...fe2fc77.html" title="Last updated on Sep 26, 2024, 9:44 PM UTC (fe2fc77)">Diff</a>

Define MediaStreamTrack.[[Restrictable]]

---

getusermedia.html

The remove-a-track algorithm currently uses a link to itself in its step 2, making it an endless loop.
Here we're not calling that algorithm again, we're just using the track set's remove method (from infra: https://infra.spec.whatwg.org/#list-remove).
(Ps: [editorial] and [non-substantive])
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Dec 3, 2024, 8:10 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL]([object Object])
```
Timed out after waiting 30000ms
```
_If you don't have …

Prevent remove-a-track to recurse.

---

getusermedia.html

Fixes #1024.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/1025.html" title="Last updated on Dec 19, 2024, 3:41 PM UTC (83e2e36)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/1025/97bb70a...jan-ivar:83e2e36.html" title="Last updated on Dec 19, 2024, 3:41 PM UTC (83e2e36)">Diff</a>

Missed a spot that should use HTMLMediaElement's potentially playing definition

---

getusermedia.html

This will help https://github.com/w3c/mediacapture-main/issues/1019 as devices will be exposed if:
- User granted access to camera and or microphone
- But somehow capture failed to start (NotReadableError or AbortError)
Before this PR, devices would be exposed if user granted access and capture did start properly.
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/1039.html" title="Last updated on Apr 24, 2025, 9:26 AM UTC (3c58796)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/1039/4d96849...youennf:3c58796.html" title="Last updated on Apr 24, 2025, 9:26 AM UTC (3c58796)">Diff</a>

Set device information exposure to true once permission is granted and before starting to capture devices

---

getusermedia.html

Partially fixes https://github.com/w3c/mediacapture-main/issues/1019
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/1038.html" title="Last updated on Apr 24, 2025, 9:04 AM UTC (59f620c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/1038/4d96849...youennf:59f620c.html" title="Last updated on Apr 24, 2025, 9:04 AM UTC (59f620c)">Diff</a>

Extend device exposure to camera if microphone is in use and vice versa

---

getusermedia.html

Fixes https://github.com/w3c/mediacapture-main/issues/910
***
<a href="https://pr-preview.s3.amazonaws.com/youennf/mediacapture-main/pull/1034.html" title="Last updated on Apr 24, 2025, 7:59 AM UTC (2403b09)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/1034/4d96849...youennf:2403b09.html" title="Last updated on Apr 24, 2025, 7:59 AM UTC (2403b09)">Diff</a>

Add guidelines for garbage collecting MediaStream and MediaStreamTrack objects

---

getusermedia.html

I have a blog post linking to a note in the spec, but the link isn't stable (alternating between `#h-note-37` and `#h-note-38`). This adds a stable reference for it (`#note-device-enumeration`) to encourage quoting.
***
<a href="https://pr-preview.s3.amazonaws.com/jan-ivar/mediacapture-main/pull/1049.html" title="Last updated on Jun 24, 2025, 11:16 PM UTC (e0ac2a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/1049/c06d1de...jan-ivar:e0ac2a8.html" title="Last updated on Jun 24, 2025, 11:16 PM UTC (e0ac2a8)">Diff</a>

Add stable link to note on device selection

---

getusermedia.html

***
<a href="https://pr-preview.s3.amazonaws.com/ahmedmoussa10/mediacapture-main/pull/1055.html" title="Last updated on Sep 25, 2025, 2:24 PM UTC (6a1caa0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/mediacapture-main/1055/6dd4900...ahmedmoussa10:6a1caa0.html" title="Last updated on Sep 25, 2025, 2:24 PM UTC (6a1caa0)">Diff</a>

Clarify that bare values are only treated as `exact` iff they are present in an advanced ConstraintSet
